[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add= '''
nnoremap [LSP] <Nop>
nmap <Leader>c [LSP]

function! s:on_lsp_buffer_enabled() abort
  setlocal omnifunc=lsp#complete
  setlocal signcolumn=yes
  if exists('+tagfunc') | setlocal tagfunc=lsp#tagfunc | endif
  nmap <silent><buffer> [LSP]d <plug>(lsp-definition)
  nmap <silent><buffer> [LSP]s <plug>(lsp-document-symbol-search)
  nmap <silent><buffer> [LSP]S <plug>(lsp-workspace-symbol-search)
  nmap <silent><buffer> [LSP]R <plug>(lsp-references)
  nmap <silent><buffer> [LSP]i <plug>(lsp-implementation)
  nmap <silent><buffer> [LSP]D <plug>(lsp-peek-definition)
  nmap <silent><buffer> [LSP]r <plug>(lsp-rename)
  nmap <silent><buffer> [c <plug>(lsp-previous-diagnostic)
  nmap <silent><buffer> ]c <plug>(lsp-next-diagnostic)
  nmap <silent><buffer> [LSP]h <plug>(lsp-hover)
  nmap <silent><buffer> [LSP]a <plug>(lsp-code-action)
  nmap <silent><buffer> [LSP]l <plug>(lsp-code-lens)
  augroup lsp_oparate_floating
    autocmd!
    autocmd User lsp_float_opened nnoremap <silent><buffer> <expr><c-f> lsp#scroll(+4)
    autocmd User lsp_float_opened nnoremap <silent><buffer> <expr><c-b> lsp#scroll(-4)
    autocmd User lsp_float_closed nunmap <silent><buffer> <expr><c-f>
    autocmd User lsp_float_closed nunmap <silent><buffer> <expr><c-b>
  augroup END

  let g:lsp_format_sync_timeout = 1000
  autocmd! BufWritePre * call execute('LspDocumentFormatSync')

  " refer to doc to add more commands
endfunction

augroup lsp_install
    autocmd!
  " call s:on_lsp_buffer_enabled only for languages that has the server registered.
  autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'

