[[plugins]]
repo = 'Lokaltog/vim-easymotion'
hook_add = '''
map <Leader> <Plug>(easymotion-prefix)
let g:EasyMotion_do_mapping = 0 " Disable default mappings

map <Leader>l <Plug>(easymotion-fl)
map <Leader>h <Plug>(easymotion-Fl)
map <Leader>L <Plug>(easymotion-tl)
map <Leader>H <Plug>(easymotion-Tl)

map f <Plug>(easymotion-bd-fl)
map t <Plug>(easymotion-bd-tl)


" Jump to anywhere you want with minimal keystrokes, with just one key binding.
" `;{char}{char}{label}`
" Need one more keystroke, but on average, it may be more comfortable.
map ; <Plug>(easymotion-bd-f2)
nmap ; <Plug>(easymotion-overwin-f2)

" Turn on case insensitive feature
let g:EasyMotion_smartcase = 1

" Word motions
map <Leader>w <Plug>(easymotion-wl)
map <Leader>W <Plug>(easymotion-Wl)
map <Leader>b <Plug>(easymotion-bl)
map <Leader>B <Plug>(easymotion-Bl)
map <Leader>e <Plug>(easymotion-el)
map <Leader>E <Plug>(easymotion-El)
map <Leader>ge <Plug>(easymotion-gel)
map <Leader>gE <Plug>(easymotion-gEl)

" JK motions: Line motions
let g:EasyMotion_startofline=0
map <Leader>j <Plug>(easymotion-j)
map <Leader>k <Plug>(easymotion-k)
'''
