[[plugins]]
repo = 'Lokaltog/vim-easymotion'
hook_add = '''
map <Leader> <Plug>(easymotion-prefix)
let g:EasyMotion_do_mapping = 0 " Disable default mappings

map f <Plug>(easymotion-fl)
map t <Plug>(easymotion-tl)
map F <Plug>(easymotion-Fl)
map T <Plug>(easymotion-Tl)

" Jump to anywhere you want with minimal keystrokes, with just one key binding.
" `;{char}{char}{label}`
" Need one more keystroke, but on average, it may be more comfortable.
map ; <Plug>(easymotion-overwin-f2)

" Turn on case insensitive feature
let g:EasyMotion_smartcase = 1

" JK motions: Line motions
let g:EasyMotion_startofline=0
map <Leader>j <Plug>(easymotion-j)
map <Leader>k <Plug>(easymotion-k)
'''
