[[plugins]]
repo = 't9md/vim-textmanip'
hook_source = '''
" c.f. http://vim-jp.org/vim-users-jp/2011/07/18/Hack-223.html
" 選択したテキストの移動
vmap <A-j> <Plug>(Textmanip.move_selection_down)
vmap <A-k> <Plug>(Textmanip.move_selection_up)
vmap <A-h> <Plug>(Textmanip.move_selection_left)
vmap <A-l> <Plug>(Textmanip.move_selection_right)

" 行の複製
vmap <A-d> <Plug>(Textmanip.duplicate_selection_v)
nmap <A-d> <Plug>(Textmanip.duplicate_selection_n)
'''
