[[plugins]]
repo = 'shun/ddc-vim-lsp'
on_source = ['ddc.vim', 'vim-lsp']

[[plugins]]
repo = 'Shougo/ddc-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'matsui54/ddc-buffer'
on_source = 'ddc.vim'

[[plugins]]
repo = 'matsui54/ddc-dictionary'
on_source = 'ddc.vim'

[[plugins]]
repo = 'takker99/ddc-bitap'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['denops.vim', 'context_filetype.vim']
on_event = 'InsertEnter'
hook_source = '''
call ddc#custom#patch_global('sources', [
  \ 'vim-lsp',
  \ 'buffer',
  \ 'dictionary'
\])
call ddc#custom#patch_global('sourceParams', {
  \ 'dictionary': {'dictPaths': 
    \ ['/usr/share/dict/american-english',
    \ '/usr/share/dict/words'],
    \ 'smartCase': v:true,
    \ 'showMenu': v:false,
  \ },
  \ 'buffer': {'requireSameFiletype': v:false},
\})
call ddc#custom#patch_global('sourceOptions', {
  \ 'vim-lsp': {
  \   'mark': 'lsp',
  \   'forceCompletionPattern': '\.\w*|:\w*|->\w*',
  \  },
  \ 'around': {'mark': 'A'},
  \ 'buffer': {'mark': 'B'},
  \ 'dictionary': {'mark': 'D'},
  \ '_': {
  \   'ignoreCase': v:true,
  \   'minAutoCompleteLength': 1,
  \   'maxCandidates': 50,
  \   'matchers': ['matcher_bitap'],
  \   'sorters': ['sorter_bitap'],
  \ }
\})

" mappings
" <TAB>: completion.
inoremap <silent><expr> <TAB>
      \ pumvisible() ? '<C-n>' :
      \ (col('.') <= 1 <Bar><Bar> getline('.')[col('.') - 2] =~# '\s') ?
      \ '<TAB>' : ddc#map#manual_complete()

" <S-TAB>: completion back.
inoremap <expr><S-TAB>  pumvisible() ? '<C-p>' : '<C-h>'

call ddc#enable()
'''
