[[plugins]]
repo = 'mbbill/undotree'
hook_source = '''
let g:undotree_WindowLayout = 1         " undotree on the left, diff window below
let g:undotree_ShortIndicators = 1      " Show short time indicators
let g:undotree_SplitWidth = 10          " Width of the undotree window
let g:undotree_SetFocusWhenToggle = 1   " Focus the undotree window when opened
"let g:undotree_DiffAutoOpen = 0         " Disable the diff window at startup
let g:undotree_DiffpanelHeight = 5      " Height of the diff window
"let g:undotree_HighlightChangedText = 0 " Disable highlighting of changed text
" Toggle undotree
noremap <Leader>u :UndotreeToggle<CR>

" Key bindings inside the undotree buffer
function! g:Undotree_CustomMap()
    nmap <silent> <buffer> <Esc> q
    nmap <silent> <buffer> h ?
endfunction
'''
